import yaml
import sys


with open("config.yaml", "r") as f:
    cfg = yaml.safe_load(f)

hosts = cfg.get("host", [])
if not isinstance(hosts, list):
    print("config.yaml 中的 host 字段不是列表，退出")
    sys.exit(1)

lines = []
for entry in hosts:
    ip = entry.get("ipaddr")
    domain = entry.get("domain")
    if ip and domain:
        lines.append(f"{ip}\t{domain}")
    else:
        print("忽略无效条目：", entry)

with open("/etc/hosts", "a") as f:
    f.write("# Generated by script\n")
    for line in lines:
        print(line)
        f.write(line + "\n")

print("更新 /etc/hosts 完成")
